apply schedule directive to `omp for` instead of `omp parallel`
problem:
```
./autogen.sh
./configure --enable-openmp
make
```
will refuse to compile with message:
```
error: ‘schedule’ is not valid for ‘#pragma omp parallel’
```

however, things compile well with:
```
./autogen.sh
./configure
make
```

which makes sense, as openmp is not even enabled...

I would like also to acknowledge in this commit that Bart reviewed the
previous commit and merged it right away with a comment:
> (the change is safe enough to assume it will not break things).